### ISSUE TITLE
Change white box in Android Lollipop dialog to match background?

### ISSUE THREAD

**Issue by wasimxyz** [cketti/ckChangeLog#19]
Is there any way to change the background of the Changelog dialog for Android Lollipop's new dialogs? See image below.

![screenshot_2014-12-03-19-27-22](https://cloud.githubusercontent.com/assets/7220175/5293229/c0047a6a-7b22-11e4-8fcb-d875c1b53c18.png)

**Comment by tral** [comment]
Hello. It works fine. 
But how can I also change the header and the footer of a dialog? It's still grey...

**Comment by cketti** [comment]
The sample code shows how to use a specific theme for the dialog. For more information on how to use themes see here: https://developer.android.com/guide/topics/ui/themes.html
