### ISSUE TITLE
Library can't be imported into Android Studio

### ISSUE THREAD

**Issue by denisk20** [cketti/ckChangeLog#23]
Error:No such property: nexusUsername for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer

Looks like `android-mvn-push.gradle` needs to be modified to provide some dummy default values for maven username and password. I can create a pull request if you don't mind.

**Comment by cketti** [comment]
> I can create a pull request if you don't mind.

That would be nice. Please go for it.

**Comment by denisk20** [comment]
Here you go:
https://github.com/cketti/ckChangeLog/pull/24

**Comment by cketti** [comment]
Fixed with the merge of pull request #25. Thank you!
