### ISSUE TITLE
.getLogFragment()

### ISSUE THREAD

**Issue by pawelantczak** [cketti/ckChangeLog#26]
Hello.
Do you have plans to support fragments?
I mean, that instead of dialog, you will return fragment.

**Comment by cketti** [comment]
With fragments you have the choice between native and support fragments. Adding support for the latter requires a dependency to the support library. To support native fragments we'd need `minSdkVersion=11`. I don't like any of these options.

The good news is, that it's easy to write a `ChangeLogFragment` yourself. A very basic version looks like this:

```java
public class ChangeLogFragment extends Fragment {
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        Context context = inflater.getContext();

        WebView webView = new WebView(context);
        ChangeLog changeLog = new ChangeLog(context);
        String changeLogText = changeLog.getFullLog();
        webView.loadData(changeLogText, "text/html", "UTF-8");

        return webView;
    }
}
```

`ChangeLog.getLog()` and `ChangeLog.getFullLog()` should give you all you need.
If you don't want to use a `WebView` you can call `ChangeLog.getChangeLog()` and render the changes yourself.

**Comment by pawelantczak** [comment]
Avoiding support lib dependency sounds reasonable.
Using native fragments is pointless.
Seems like my idea was not so very good :]
Thanks.
