### ISSUE TITLE
Changelog dialog is displayed twice when orientation changes

### ISSUE THREAD

**Issue by MasoodFallahpoor** [cketti/ckChangeLog#29]
If screen is rotated while the changelog dialog is  being displayed, the dialog disappears and in the next run of the app the changelog dialog is displayed again.

**Comment by cketti** [comment]
The standard caveats for dialog lifecycle management apply.
You have to make sure that either the dialog is retained (e.g. by manually wrapping it in a DialogFragment) or that you recreate the dialog on orientation changes.

The new app version is only considered to be the current version after the dialog has been discarded by pressing the "Ok" button. So when you never close the dialog the regular way `isFirstRun()` will still return `true` the next time it is called.
