### ISSUE TITLE
Values in pt br

### ISSUE THREAD

**Issue by sagits** [cketti/ckChangeLog#35]
Hi, may you add these values to values-pt for portuguese language?

<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:xliff="urn:oasis:names:tc:xliff:document:1.2">
    <string name="changelog_full_title">Novidades</string>
    <string name="changelog_title">Novidades</string>
    <string name="changelog_ok_button">OK</string>
    <string name="changelog_show_full">Mais…</string>

```
<string name="changelog_version_format">Versão <xliff:g id="version_name">%s</xliff:g></string>
```

</resources>

**Comment by cketti** [comment]
Hi. Can you please send a pull request?
