### ISSUE TITLE
Dark theme not fully applied

### ISSUE THREAD

**Issue by smichel17** [cketti/ckChangeLog#40]
>>>>>>>>>>>> ![screenshot_1490217887](https://cloud.githubusercontent.com/assets/6563664/24221466/c6950f14-0f24-11e7-95c1-1b724e695716.png)

Screenshot kind of says it all. I know k9 mail is affected by this, too.

**Comment by cketti** [comment]
The changelog is rendered in a `WebView`. If you wish to change the appearance of the rendered HTML you have to provide the CSS necessary for that.
