### ISSUE TITLE
Disable translations?

### ISSUE THREAD

**Issue by felixwiemuth** [cketti/ckChangeLog#41]
It is quite inconsistent if the change log is translated to languages the actual app is not. Is there an easy way to disable translations of the change log for certain languages?

The only ways I can think of:
- Actually create translations for the languages ckChangeLog is translated for by copying `strings.xml` from the default values
- Create own keys for the change log strings and set them at the dialog obtained by `getLogDialog()` (not very elegant)

**Comment by cketti** [comment]
You can configure the Android Gradle plugin to only keep resources for languages you explicitly support. See https://developer.android.com/studio/build/shrink-code#unused-alt-resources
