### ISSUE TITLE
Callback when dialog is closed

### ISSUE THREAD

**Issue by johnjohndoe** [cketti/ckChangeLog#49]
It would be great to being able to register for a **callback** which is invoked once the dialog is **closed**. This would enable users to coordinate with other dialogs such as Android permission dialogs.

**Comment by cketti** [comment]
I don't want to extend the functionality of the dialog UI. However, with version 2's core artifact the code necessary to create such a dialog should be fairly minimal. A snapshot of 2.0.0 is available in Maven Central's snapshot repository.

On a side note: Having to coordinate multiple dialogs is a good indicator that you have too many dialogs :smile: Consider using a different approach to displaying the change log. Maybe a bottom sheet that peeks in a little bit and can be easily dismissed?
