### ISSUE TITLE
do not show changelog if user first time installing app

### ISSUE THREAD

**Issue by photog0411** [cketti/ckChangeLog#50]
No point in showing changelog if user first time installing app. They don't need to know what's changed then and it's just another dialog they have to click through.

I know you don't update this library anymore but that would be very nice thing to have.

**Comment by cketti** [comment]
You can already implement this behavior using `isFirstRunEver()`.

**Comment by photog0411** [comment]
I tried that, but it didn't seem to work. It still showed me the changelog when I installed the app on a fresh emulator, first run.

This is how I have it written:

```
                ChangeLog changeLog = new ChangeLog(this);
                if (changeLog.isFirstRunEver()) {
                    changeLogDialog = changeLog.getLogDialog();
                     changeLogDialog.show();
                }
```

Did I write it wrong?

**Comment by cketti** [comment]
You probably want

```java
ChangeLog changeLog = new ChangeLog(this);
if (changeLog.isFirstRun() && !changeLog.isFirstRunEver()) {
    changeLog.getLogDialog().show();
}
```

**Comment by photog0411** [comment]
thanks for the help, but it's still not working with that.

Now with that implementation, the changelog doesn't show at all, neither on first install or on an update to a current install.

**Comment by photog0411** [comment]
not that it should matter, but I also tried it with double IF statements and it didn't work that way either

```
        ChangeLog changeLog = new ChangeLog(this);
            if (changeLog.isFirstRun()) {
               if (!changeLog.isFirstRunEver()) {
                   changeLogDialog = changeLog.getLogDialog();
                   changeLogDialog.show();
               }
            }
```

**Comment by cketti** [comment]
My bad. If you skip showing the dialog the last known version isn't updated. Try this:

```java
ChangeLog changeLog = new ChangeLog(this);
if (changeLog.isFirstRunEver()) {
    changeLog.skipLogDialog();
} else if (changeLog.isFirstRun()) {
    changeLog.getLogDialog().show();
}
```

**Comment by photog0411** [comment]
that did the trick, thank you!

you should put this in your readme.md file so other ppl will know.

closing this issue now.
