### ISSUE TITLE
getLogDialog is blank

### ISSUE THREAD

**Issue by yax51** [cketti/ckChangeLog#58]
When trying to use getLogDialog() to show an abbreviated changelog, the dialog appears, but is blank. Clicking "More..." displays the full log.

Here is my changelog_master.xml
```
<changelog>
    <release version="1.1" versioncode="2" >
       <change>Added Ability to view Version History from the "About" screen.</change>
    </release>
    <release version="1.0" versioncode="1" >
        <change>Added Ability to check for and install updates</change>
    </release>
</changelog>
```
I'm updating from version "1.0" version code 1 to version "1.1" versioncode 2. The update works as expected, and the dialog is showing as it should be. I would expect it to show the release notes for version "1.1" versioncode 2 after an update.

Thanks!

**Comment by cketti** [comment]
The "what's new" dialog only shows changes since the last time any changelog dialog was displayed. If the app wasn't updated, there's nothing new to show and the list of changes is empty. That's why the README suggests to use the following code:

```java
ChangeLog cl = new ChangeLog(this);
if (cl.isFirstRun()) {
    cl.getLogDialog().show();
}
```

**Comment by yax51** [comment]
> The "what's new" dialog only shows changes since the last time any changelog dialog was displayed. If the app wasn't updated, there's nothing new to show and the list of changes is empty. That's why the README suggests to use the following code:
> 
> ```java
> ChangeLog cl = new ChangeLog(this);
> if (cl.isFirstRun()) {
>     cl.getLogDialog().show();
> }
> ```

I am using the suggested code. 
My update flow is: 
version 1: No changelog or library in place. > Version 2: Implements library and adds changelog.
If I'm understanding right, version 2 wouldn't have anything to show as the changelog was just introduced. But version 3+ would show the current changes?

**Comment by cketti** [comment]
Try having a look at the source code to learn how the library works. It's not that much code.

`isFirstRun()` returns `true` when the last remembered version code is smaller than the current version code of the app. When there's no last remembered version code `mLastVersionCode` will be initialized with `-1` and the method will return `true`.
https://github.com/cketti/ckChangeLog/blob/cdfdbe7e6410ebfa503380b2726ce72be0d38664/ckChangeLog/src/main/java/de/cketti/library/changelog/ChangeLog.java#L231-L233

When a changelog dialog is closed using the "OK" button the current version code will be the last one that is remembered.
https://github.com/cketti/ckChangeLog/blob/cdfdbe7e6410ebfa503380b2726ce72be0d38664/ckChangeLog/src/main/java/de/cketti/library/changelog/ChangeLog.java#L298-L307

When reading the changelog for the "what's new" view, entries for versions codes smaller than or equal to the last remembered version code are skipped.
https://github.com/cketti/ckChangeLog/blob/cdfdbe7e6410ebfa503380b2726ce72be0d38664/ckChangeLog/src/main/java/de/cketti/library/changelog/ChangeLog.java#L532-L534

If your changelog doesn't contain entries with a version code larger than the last remembered version code `isFirstRun()` might return `true` but the "what's new" list is still empty.

**Comment by yax51** [comment]
Gotcha, that makes sense.
As there is no last remembered version code in version 2, of course the what's new list would be empty.
After testing it with version 3, the what's new list shows the correct entry and works as expected.

Thank you so much for your help! 
I'll go ahead and close this.
