### ISSUE TITLE
Dialog won't load content and rapidly resizes

### ISSUE THREAD

**Issue by bdonahue** [cketti/ckChangeLog#6]
When QAing this library we ran into a case where the change log dialog will not load the contents and constantly changes sizes. This does not happen every time or on every phone but some phones we tested with this is the behavior some of the time. 

We know it has something to do with the CSS being applied because when we comment out the CSS we cannot reproduce the issue. Also as you can see in the video it looks like the dialog renders properly for a split second after the dismiss button is clicked.

Please see video of issue at: https://dl.dropboxusercontent.com/u/66318395/VisualGlitching.MOV

**Comment by cketti** [comment]
I read that the HTC One X got an update to Android 4.2.2. Hopefully this issue was fixed.

Anyway, I think there's no point in keeping this issue open.
